<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <Target Name="CopyCorkSchema" AfterTargets="Build">
    <ItemGroup>
      <_CorkSchema Include="$(MSBuildThisFileDirectory)..\appsettings-schema.Cork.json" />
    </ItemGroup>

    <Copy
      SourceFiles="@(_CorkSchema)"
      DestinationFiles="$(MSBuildProjectDirectory)\appsettings-schema.Cork.json"
      SkipUnchangedFiles="true" />
  </Target>

</Project>
