<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
  </PropertyGroup>

  <PropertyGroup>
    <Product>Umbraco.Community.Cork</Product>
    <PackageId>Umbraco.Community.Cork</PackageId>
    <Title>Cork </Title>
    <Description>...</Description>
    <PackageTags>umbraco;umbraco-marketplace</PackageTags>
    <Authors>Gregory Dove, Luke Hook, Sam Forrest</Authors>
    <Copyright>$([System.DateTime]::UtcNow.ToString(`yyyy`)) © Gregory Dove</Copyright>
    <PackageProjectUrl>https://github.com/g-dove/Cork</PackageProjectUrl>
    <RepositoryUrl>https://github.com/g-dove/Cork</RepositoryUrl>
    <PackageReadmeFile>README_nuget.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon></PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Web.Website" Version="*" />
    <PackageReference Include="Umbraco.Cms.Web.Common" Version="*" />
    <PackageReference Include="Umbraco.Cms.Api.Common" Version="*" />
    <PackageReference Include="Umbraco.Cms.Api.Management" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <!-- Dont include the client folder as part of packaging nuget build -->
    <Content Remove="Client\**" />

    <!-- However make the Umbraco-package.json included for dotnet pack or nuget package and visible to the solution -->
    <None Include="Client\public\umbraco-package.json" Pack="false" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\docs\README_nuget.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettings-schema.Cork.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="buildTransitive\**" Pack="true" PackagePath="buildTransitive" />
  </ItemGroup>

</Project>